package com.icechen1.omnible.app;

/**
 * Created by Icechen1 on 11/03/14.
 */
public class SchoolValues {
    final static String[] names = new String[] {
            "Marianopolis College",
            "Vanier College",
            "Dawson College",
            "John Abott College",
            "Champlain College St-Lambert",
            "Collège de Maisonneuve",
            "Cégep de St-Laurent",
        	"Cégep Édouard-Montpetit",
        	"Cégep André-Laurendeau",
        	"Cégep régional de Lanaudière (L'Assomption)",
        	"Collège de Bois-de-Boulogne",
        	"Collège Jean-de-Brébeuf",
        	"Cégep du Vieux Montréal",
        	"Collège Gérald-Godin",
			"Champlain College Lennoxville",
			"Collège Ahuntsic",
			"Collège André-Grasset",
			"Cégep de Drummondville",
			"Collège LaSalle",
			"Cégep régional de Lanaudière à Terrebonne",
			"Cégep de Saint-Jérôme",
			"Cégep de Sept-Îles",
			"Cégep de l'Abitibi-Témiscamingue",
			"Cégep Limoilou",
			"Cégep de Sainte-Foy",
			"Collège de Valleyfield",
			"Collège Laflèche",
			"Cégep de Trois-Rivières"};
    final static String[] urls = new String[] {
            "https://marianopolis.omnivox.ca/Mobl/",
            "https://vaniercollege.omnivox.ca/Mobl/",
            "https://dawsoncollege.omnivox.ca/Mobl/",
            "https://johnabbott.omnivox.ca/Mobl/",
            "https://champlaincollege-st-lambert.omnivox.ca/Mobl/",
            "https://cmaisonneuve.omnivox.ca/Mobl/",
            "https://cegep-st-laurent.omnivox.ca/Mobl/",
        	"https://cegepmontpetit.omnivox.ca/Mobl/",
        	"https://claurendeau.omnivox.ca/Mobl/",
        	"https://collanaud-assomption.omnivox.ca/Mobl/",
        	"https://bdeb.omnivox.ca/Mobl/",
        	"https://brebeuf.omnivox.ca/Mobl/",
        	"https://cvm.omnivox.ca/Mobl/",
        	"https://cgodin.omnivox.ca/Mobl/",
			"https://champlaincollege-lennoxville.omnivox.ca/Mobl/",
			"https://collegeahuntsic.omnivox.ca/Mobl/‎",
			"https://grasset.omnivox.ca/Mobl/",
			"https://cdrummond.omnivox.ca/‎Mobl/",
			"https://collegelasalle.omnivox.ca/Mobl/",
			"https://collanaud-terrebonne.omnivox.ca/‎Mobl/",
			"https://cstj.omnivox.ca/‎Mobl/",
			"https://cegep-sept-iles.omnivox.ca/‎Mobl/",
			"https://cegepat.omnivox.ca/‎Mobl/",
			"https://climoilou.omnivox.ca/‎Mobl/",
			"https://cegep-ste-foy.omnivox.ca/‎Mobl/",
			"https://colval.omnivox.ca/‎Mobl/",
			"https://clafleche.omnivox.ca/‎Mobl/",
			"https://cegeptr.omnivox.ca/Mobl/"};
}
